zstyle :compinstall filename '/home/manos/.zshrc'
autoload -Uz promptinit
promptinit

eval "$(zoxide init zsh)" # Add zoxide

# Append .bin to path
path+=("${HOME}/.bin")
path+=("${HOME}/.local/bin")
export PATH

export SPOTIPY_CLIENT_ID=2c3af1c2720d48449c8134e5d86078e9
export SPOTIPY_CLIENT_SECRET=c96d4cf1ee5e42debb6bf39f38b25185

# Aliases
# Easier Navigation
alias d="cd ~/Documents"
alias dl="cd ~/Downloads"
alias gt="cd ~/Documents/Github"
alias cf="cd ~/.config"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."


# Shortcuts
# Finds unused packages (orhans) and removes them
alias clean='pacman -Qtdq | sudo pacman -Rns -'
alias sedit="SUDO_EDITOR=\"emacsclient\" sudo -e"
alias duck='ddgr -j'
alias te='emacsclient -t'
alias temacs='emacsclient -t'
alias emacs='emacscliententry'
alias restart-emacs='systemctl restart --user emacs.service'
alias open='xdg-open'
alias update='sudo pacman -Syu'
alias wiki='ddgr -j \!w'
alias yeet='sudo pacman -Rns'
alias mm='micromamba'

# ls shortcuts
alias ll='la -l'
alias ls='ls --color=auto'
alias la='ls -aA'

# Kitty specific alias
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
export EDITOR="emacsclient -t"
bindkey "^[[3~" delete-char
unsetopt beep
#unsetopt prompt_cr prompt_sp
export RANGER_LOAD_DEFAULT_RC=FALSE


# Files to source
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

bindkey -M emacs '^P' up-line-or-history
bindkey -M emacs '^N' down-line-or-history


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/usr/bin/micromamba';
export MAMBA_ROOT_PREFIX='/home/manos/.micromamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<
micromamba activate base
